name = "hanallcompany-ebook"
compatibility_date = "2026-01-06"

# Cloudflare Pages 정적 산출물 경로 (Next.js export 결과물)
pages_build_output_dir = "./out"

# Cloudflare 계정 ID (CI에서 환경변수로 덮어씌우도록 권장)
account_id = "6c9a5bdb861dab35086248dce9e10992"

